package dec27;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
public class UsingXpath {
public static void main(String[] args) throws Throwable {
		WebDriver driver=new ChromeDriver();
		driver.get("http://newtours.demoaut.com/mercuryregister.php");
		driver.manage().window().maximize();
		Thread.sleep(2000);
		WebElement firstName=driver.findElement(By.xpath("//input[@name='firstName']"));
		firstName.clear();
		firstName.sendKeys("venkatesh");
		Thread.sleep(2000);
		WebElement lastName=driver.findElement(By.xpath("//input[@name='lastName']"));
		lastName.clear();
		lastName.sendKeys("kilaru");
		Thread.sleep(2000);
		WebElement phone=driver.findElement(By.xpath("//input[@name='phone']"));
		phone.clear();
		phone.sendKeys("901234568");
		Thread.sleep(2000);
		WebElement userName=driver.findElement(By.xpath("//input[@id='userName']"));
		userName.clear();
		userName.sendKeys("venkagstwrv56@gmail.com");
		Thread.sleep(2000);
		WebElement address1=driver.findElement(By.xpath("//input[@name='address1']"));
		address1.clear();
		address1.sendKeys("7-30,NTR center");
		Thread.sleep(2000);
		WebElement city=driver.findElement(By.xpath("//input[@name='city']"));
		city.clear();
		city.sendKeys("Hyderabad");
		Thread.sleep(2000);
		WebElement state=driver.findElement(By.xpath("//input[@name='state']"));
		state.clear();
		state.sendKeys("Telengana");
		Thread.sleep(2000);
		WebElement postalcode=driver.findElement(By.xpath("//input[@name='postalCode']"));
		postalcode.clear();
		postalcode.sendKeys("432543");
		Thread.sleep(2000);
		WebElement country=driver.findElement(By.xpath("//select[@name='country']"));
		country.sendKeys("INDIA");
		Thread.sleep(2000);
		WebElement email=driver.findElement(By.xpath("//input[@id='email']"));
		email.clear();
		email.sendKeys("venky123");
		Thread.sleep(2000);
		WebElement password=driver.findElement(By.xpath("//input[@name='password']"));
		password.clear();
		password.sendKeys("123456789");
		Thread.sleep(2000);
		WebElement confirmPassword=driver.findElement(By.xpath("//input[@name='confirmPassword']"));
		confirmPassword.clear();
		confirmPassword.sendKeys("123456789");
		Thread.sleep(2000);
		WebElement register=driver.findElement(By.xpath("//input[@name='register']"));
		register.sendKeys("");
		driver.close();
	}
}
